CREATE DATABASE IF NOT EXISTS TaskFlow;

USE TaskFlow;

CREATE TABLE IF NOT EXISTS USUARIO(
    NOMBRE_USUARIO VARCHAR(30) NOT NULL PRIMARY KEY,
    NOMBRE_PREFERIDO VARCHAR(50) NOT NULL,
    CONTRASENIA VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREA(
    ID_TAREA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TAREA VARCHAR(30) NOT NULL,
    DESCRIPCION VARCHAR(100),
    FECHA_HORA_CREACION DATETIME NOT NULL,

);

CREATE TABLE IF NOT EXISTS TAREAS_USUARIO (
    NOM_USR VARCHAR(30) NOT NULL PRIMARY KEY,
    ID_TAR INT NOT NULL PRIMARY KEY,
    FOREIGN KEY(NOM_USR) REFERENCES USUARIO(NOMBRE_USUARIO),
    FOREIGN KEY(ID_TAR) REFERENCES TAREA(ID_TAREA)
);
