CREATE DATABASE IF NOT EXISTS TaskFlow;

USE TaskFlow;

CREATE TABLE USUARIO(
    ID_USUARIO INT AUTO_INCREMENT,
    NOMBRE_PREFERIDO VARCHAR(50) NOT NULL,
    NOMBRE_USUARIO VARCHAR(30) NOT NULL,
    CONTRASENIA VARCHAR(30) NOT NULL
);

CREATE TABLE TAREA(
    ID_TAREA INT AUTO_INCREMENT,
    NOMBRE_TAREA VARCHAR(30) NOT NULL,
    DESCRIPCION VARCHAR(100),
    FECHA_HORA_CREACION DATETIME NOT NULL,

);
